CREATE UNIQUE NONCLUSTERED INDEX [IDX_NC_UQ_Trace_Properties__TraceName_PropertyName]
    ON [DBLog].[Trace_Properties]([TraceName] ASC, [PropertyName] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];





