/*
:SETVAR AUDITEDDB "[chc-test]"
:SETVAR SERVERAUDIT "chcmasteraudit"
:SETVAR DBAUDITNAME "chcaudit"
*/

USE $(AUDITEDDB)
GO

CREATE DATABASE AUDIT SPECIFICATION $(DBAUDITNAME)
FOR SERVER AUDIT $(SERVERAUDIT)
ADD (INSERT ON DATABASE::$(AUDITEDDB) BY [public])
WITH (STATE = ON)
GO