/*
:SETVAR AUDITEDDB "[chc-test]"
:SETVAR SERVERAUDIT "chcmasteraudit"
:SETVAR DBAUDITNAME "chcaudit"
*/

USE $(AUDITEDDB)
GO
IF NOT EXISTS(select * from sys.database_audit_specifications where name='$(DBAUDITNAME')
BEGIN
    CREATE DATABASE AUDIT SPECIFICATION $(DBAUDITNAME)
    FOR SERVER AUDIT $(SERVERAUDIT)
    ADD (INSERT ON DATABASE::$(AUDITEDDB) BY [public])
    WITH (STATE = ON)
END
GO