if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL03' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL03','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL03A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL03A','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL03B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL03B','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL01' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL01','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL01A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL01A','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL01B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL01B','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL02' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL02','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL02A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL02A','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL02B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL02B','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL03' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL03','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL03A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL03A','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PSSQL03A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PSSQL03A','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL01' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL01','AN','AN3PROD')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL01A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL01A','AN','AN3PROD')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL01B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL01B','AN','AN3PROD')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL02' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL02','AN','AN3PROD')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL02A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL02A','AN','AN3PROD')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL02B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL02B','AN','AN3PROD' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL03' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL03','AN','AN3PROD')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL03A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL03A','AN','AN3PROD' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3PRODSQL03A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3PRODSQL03A','AN','AN3PROD' )
if not exists (select 1 from [dblog].[server_error] where servername ='CORPTFS01' and serveraliasname='CP') insert into [dblog].[server_error] values ('CORPTFS01','CP','FINETRE')
if not exists (select 1 from [dblog].[server_error] where servername ='LIFESPEEPRODSQL' and serveraliasname='LS') insert into [dblog].[server_error] values ('LIFESPEEPRODSQL','LS','EBIXWEB' )
if not exists (select 1 from [dblog].[server_error] where servername ='ATLISVR' and serveraliasname='CP') insert into [dblog].[server_error] values ('ATLISVR','CP','DELPHI' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL01' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL01','AN','AN3' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL01A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL01A','AN','AN3' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL01B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL01B','AN','AN3' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL02' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL02','AN','AN3')
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL02A' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL02A','AN','AN3' )
if not exists (select 1 from [dblog].[server_error] where servername ='AN3UATSQL02B' and serveraliasname='AN') insert into [dblog].[server_error] values ('AN3UATSQL02B','AN','AN3' )
if not exists (select 1 from [dblog].[server_error] where servername ='SWARNS' and serveraliasname='CP') insert into [dblog].[server_error] values ('SWARNS','CP','FINETRE' )
