ALTER TABLE [DBLog].[Alert_Recipients]
    ADD CONSTRAINT [PK_Alert_Recipients_AlertRecipientId] PRIMARY KEY NONCLUSTERED ([AlertRecipientId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

