ALTER TABLE [DBLog].[Auditable_Logins_Custom]
    ADD CONSTRAINT [PK_Auditable_Logins_Custom] PRIMARY KEY CLUSTERED ([AccountName] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

