ALTER TABLE [DBLog].[backup_exceptions]
    ADD CONSTRAINT [PK_backup_exceptions] PRIMARY KEY CLUSTERED ([DBName] ASC, [backuptype] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

