ALTER TABLE [DBLog].[Backup_Jobs]
    ADD CONSTRAINT [PK_Backup_Jobs] PRIMARY KEY CLUSTERED ([Backup_Job_ID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);





