/*ALTER TABLE [DBLog].[BackupIntervals]
    ADD CONSTRAINT [PK_BackupIntervals] PRIMARY KEY CLUSTERED ([Interval_ID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

