ALTER TABLE [DBLog].[BCP_info]
    ADD CONSTRAINT [PK_BCP_info] PRIMARY KEY CLUSTERED ([BCP_ID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







