ALTER TABLE [DBLog].[Backup_transfer_Job]
    ADD CONSTRAINT [PK_Backup_transfer_Job] PRIMARY KEY CLUSTERED ([Transfer_ID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);





