ALTER TABLE [DBLog].[Alert_Definitions]
    ADD CONSTRAINT [PK_DBLog.Alert_Definitions] PRIMARY KEY CLUSTERED ([AlertName] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







