ALTER TABLE [DBLog].[FrequencyInfo]
    ADD CONSTRAINT [PK_DBLOG]].[FrequencyInfo] PRIMARY KEY CLUSTERED ([frequencyName] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







