ALTER TABLE [DBLog].[Errors]
    ADD CONSTRAINT [PK_dblog_Errors_ErrorID] PRIMARY KEY CLUSTERED ([ErrorID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







