ALTER TABLE [DBLog].[DBUsage]
    ADD CONSTRAINT [PK_DBUsage] PRIMARY KEY CLUSTERED ([CollectionDate] ASC, [Servername] ASC, [DatabaseName] ASC, [table_name] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);











