ALTER TABLE [DBLog].[Error_Alert]
    ADD CONSTRAINT [PK_Error_Alert_Alert_Name_ErrorID] PRIMARY KEY CLUSTERED ([Alert_Name] ASC, [ErrorID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







