ALTER TABLE [DBLog].[FTP_Jobs]
    ADD CONSTRAINT [PK_FTP_Jobs] PRIMARY KEY CLUSTERED ([FTP_Job_ID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







