ALTER TABLE [DBLog].[JobFailuresSP_LastRun]
    ADD CONSTRAINT [PK_JobFailuresSP_LastRun_RunTimeId] PRIMARY KEY NONCLUSTERED ([RunTimeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

