ALTER TABLE [DBLog].[Location_Details]
    ADD CONSTRAINT [PK_Location_Details] PRIMARY KEY CLUSTERED ([LocationID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);




