ALTER TABLE [DBLog].[server_Error]
    ADD CONSTRAINT [PK_server_Error] PRIMARY KEY CLUSTERED ([ServerName] ASC, [ServerAliasName] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);







