ALTER TABLE [DBLog].[Trace_Info]
    ADD CONSTRAINT [PK_Trace_Info] PRIMARY KEY CLUSTERED ([ROWID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);





