ALTER TABLE [DBLog].[Trace_Jobs]
    ADD CONSTRAINT [PK_Trace_Jobs] PRIMARY KEY CLUSTERED ([Tracename] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);





